[[items]]
name = 'Noun'
config_path ='./nouns-image-data.json'

[items.options]
outDir = './src/pkg'
rpc = ''

[[items]]
name = 'Wizard'
config_path ='./wizards.json'

[items.options]
outDir = './src/pkg'
rpc = ''
